FROM nginx:1.21.6

EXPOSE 8080

ENV CATALOGUE_HOST=catalogue 

COPY entrypoint.sh /root/
ENTRYPOINT ["/root/entrypoint.sh"]

COPY default.conf.template /etc/nginx/conf.d/default.conf.template
COPY static /usr/share/nginx/html
